      SUBROUTINE TRARA1(DESCR,MAP,FL,BABS,E,F,N)
C***********************************************************************
C     B / B0 CASE     JOEL STEIN     9-15-71     X2133     KMS
C   TRARA1 DOES ENERGY VALUE SEARCH FOR FLUX CALCULATION WHEN GIVEN A
C    B AND L POINT.
C***********************************************************************
C  MAP(1) IS THE FIRST WORD OF LIST
      LOGICAL S0,S1,S2
C   S0,S1,S2 ARE LOGICAL VARIABLES WHICH INDICATE WHETHER THE FLUX FOR A
C     PARTICULAR E,B,L POINT HAS ALREADY BEEN FOUND IN A PREVIOUS CALL
C     TO TRARA2.
      DIMENSION E(1),F(1),DESCR(8),MAP(1)
      NL=AMIN1(32766.,ABS(FL*DESCR(5)))
      NB =ABS(((BABS*(FL*FL*FL)/0.311653)-1) * DESCR(6))
C     NB=ABS((BABS-0.311653E0/(FL*FL*FL))*DESCR(6))
C   NL IS THE MINIMUM OF THE L VALUE OR 15.999, SCALED TO AN INTEGER BY
C     THE L SCALING FACTOR
C   NB IS THE DIFFERENCE BETWEEN THE INPUT B VALUE AND B EQUATORIAL,
C     SCALED TO AN INTEGER BY THE B SCALING FACTOR.
      I1=0
      I2=MAP(1)
      I3=I2+MAP(I2+1)
      L3=MAP(I3+1)
      E1=MAP(I1+2)/DESCR(4)
      E2=MAP(I2+2)/DESCR(4)
      S1=.TRUE.
      S2=.TRUE.
C
C   I2 IS THE NUMBER OF ELEMENTS IN THE FLUX MAP FOR THE FIRST ENERGY.
C   I3 IS THE INDEX OF THE LAST ELEMENT OF THE SECOND ENERGY MAP.
C   L3 IS THE LENGTH OF THE MAP FOR THE THIRD ENERGY.
C   E1 IS THE ENERGY OF THE FIRST ENERGY MAP (UNSCALED)
C   E2 IS THE ENERGY OF THE SECOND ENERGY MAP (UNSCALED)
C   S1 AND S2 ARE TRUE TO INDICATE THAT NO FLUXES HAVE YET BEEN FOUND.
C
      DO 3 IE=1,N
C   THE DO STATEMENT LOOPS THROUGH THE ENERGIES FOR WHICH FLUXES ARE
C     DESIRED AT THE GIVEN B,L POINT (BABS,FL).
1     IF(E(IE).LE.E2.OR.L3.EQ.0)GOTO2
C
C   THE IF STATEMENT CHECKS TO SEE IF THE INPUT ENERGY IS LESS THAN OR E
C     THE ENERGY OF THE SECOND MAP, OR IF THE LENGTH OF THE THIRD MAP IS
C     (I.E. THERE ARE NO HIGHER ENERGIES IN THE TABLE).  IF TRUE, USE TH
C     FOR THOSE TWO ENERGY MAPS TO FIND THE DESIRED FLUX AT THE DESIRED
C     ENERGY.  IF FALSE, THE ZEROTH ENERGY MAP IS DEFINED TO BE TNE FIRS
C     ENERGY MAP, THE FIRST BECOMES THE SECOND, AND THE SECOND BECOMES
C     THE THIRD.  E0,E1,E2 ARE THE ENERGIES FOR THE ZEROTH,FIRST,AND SEC
C     ENERGY MAPS.  F0,F1,F2 ARE THE FLUXES FOR THE ZEROTH, FIRST, AND
C     SECOND ENERGY MAPS AT THE B,L POINT.
C
      I0=I1
      I1=I2
      I2=I3
      I3=I3+L3
      L3=MAP(I3+1)
      E0=E1
      E1=E2
      E2=MAP(I2+2)/DESCR(4)
      S0=S1
      S1=S2
      S2=.TRUE.
      F0=F1
      F1=F2
      GOTO1
2     IF(S1)F1=TRARA2(MAP(I1+3),NL,NB)/DESCR(7)
      IF(S2)F2=TRARA2(MAP(I2+3),NL,NB)/DESCR(7)
C   THESE TWO LOGICAL IFS CALL TRARA2 FOR THE FLUX FROM THE FIRST AND
C     SECOND ENERGY MAPS AT THE B,L POINT IF THEY HAVE NOT ALREADY BEEN
      S1=.FALSE.
      S2=.FALSE.
C   S1 AND S2 ARE FALSE SINCE F1 AND F2 ARE NOW FOUND.
      F(IE)=F1+(F2-F1)*(E(IE)-E1)/(E2-E1)
C
C   INTERPOLATE FOR THE FLUX F(IE) USING THE FLUXES AND ENERGIES FOR MAP
C     ONE AND TWO.
C   THE FOLLOWING COMMENTS APPLY TO THE REMAINING PROGRAM STATEMENTS.
C   IF THE FLUX F2 FOR THE SECOND ENERGY MAP IS GREATER THAN ZERO, OR TH
C     ZEROTH ENERGY MAP HAS NOT BEEN DEFINED, THE FINAL FLUX IS THE MAXI
C     OF THE INTEROOLATED FLUX OR ZERO.  IF THE FLUX FOR THE SECOND ENER
C     MAP IS EQUAL TO ZERO, AND THE ZEROTH ENERGY MAP HAS BEEN DEFINED,
C     THEN INTERPOLATE FOR THE FLUX USING THE ZEROTH AND FIRST ENERGY MA
C     CHOOSE THE MINIMUM OF THE TWO INTERPOLATIONS, AND THEN THE MAXIMUM
C     CHOICE AND ZERO FOR THE FINAL FLUX VALUE.
C
      IF(F2.GT.0.)GOTO3
      IF(I1.EQ.0)GOTO3
      IF(S0)F0=TRARA2(MAP(I0+3),NL,NB)/DESCR(7)
      S0=.FALSE.
      F(IE)=AMIN1(F(IE),F0+(F1-F0)*(E(IE)-E0)/(E1-E0))
3     F(IE)=AMAX1(F(IE),0.)
      RETURN
      END
