MODULE AACGM
DESCRIPTION AACGM
VERSION 1.5
SOURCE Haje Korth, JHU/APL
BUILD_DATE June 2005
FUNCTION AACGM_MLT 3 3 KEYWORDS
FUNCTION AACGM_MLONG 3 3
PROCEDURE AACGM_CONV_COORD 6 6 KEYWORDS
PROCEDURE AACGM_LOAD_COEF 1 1
