rm ./IAGA/index.html*
rm ./IAGA/index.html?C=M;O=A*
rm ./IAGA/index.html?C=S;O=A*
rm ./IAGA/index.html?C=D;O=A*
rm ./IAGA/vmod/index.html?C=N;O=D*
rm ./IAGA/vmod/index.html?C=M;O=A*
rm ./IAGA/vmod/index.html?C=S;O=A*
rm ./IAGA/vmod/index.html?C=D;O=A*
rm ./IAGA/vmod/index.html?C=N;O=A*
rm ./IAGA/vmod/index.html?C=M;O=D*
rm ./IAGA/vmod/index.html?C=S;O=D*
rm ./IAGA/vmod/index.html*
rm ./IAGA/index.html?C=N;O=A*
rm ./IAGA/index.html?C=M;O=D*
rm ./IAGA/index.html*
rm ./IAGA/index.html?C=D;O=D*
