
#define  SccsId_hkadidh_h  "@(#)hkadidh.h	1.1, 05/23/00"

/* REF: Table A-1: Data Stream ADID Summary CL-ESC-ID-0001 Iussue 2.5 */
#ifndef _hkadid_h
#define _hkadid_h
typedef enum {
HkextractAdidECLUD001 = 20,	 /* Cluster CD-ROM directory tree listing */
HkextractAdidECLUD002 = 21,	 /* Cluster CD-ROM cumulative index file format */
HkextractAdidECLUD003 = 22,	 /* Catalogue format for Cluster off-line delivery */
HkextractAdidECLUD004 = 23,	 /* Catalogue format for Cluster on-line delivery */
HkextractAdidECLUD005 = 24,	 /* Acknowledgement format for Cluster off-line delivery */
HkextractAdidECLUD006 = 25,	 /* Volume production information format for Cluster off-line delivery */
HkextractAdidECLUD007 = 0,	 /* Mast catalogue of all Cluster data available */
HkextractAdidECLUA001 = 1,	 /* Long Term Orbit File */
HkextractAdidECLUA002 = 2,	 /* Long Term Event File */
HkextractAdidECLUA003 = 3,	 /* Short Term Orbit File */
HkextractAdidECLUA004 = 4,	 /* Short Term Event File */
HkextractAdidECLUA005 = 5,	 /* Spacecraft Altitude and Spin Rate Entry */
HkextractAdidECLUA006 = 6,	 /* Time Calibration File Entry */
HkextractAdidECLUA007 = 7,	 /* Command History File Entry */
HkextractAdidECLUP101 = 200,	 /* Housekeeping Parameter Definition File for EDI on CLUSTER 1 */
HkextractAdidECLUP102 = 201,	 /* Housekeeping Parameter Definition File for FGM on CLUSTER 1 */
HkextractAdidECLUP103 = 202,	 /* Housekeeping Parameter Definition File for CIS on CLUSTER 1 */
HkextractAdidECLUP104 = 203,	 /* Housekeeping Parameter Definition File for PEACE on CLUSTER 1 */
HkextractAdidECLUP105 = 204,	 /* Housekeeping Parameter Definition File for RAPID on CLUSTER 1 */
HkextractAdidECLUP106 = 205,	 /* Housekeeping Parameter Definition File for WEC on CLUSTER 1 */
HkextractAdidECLUP107 = 206,	 /* Housekeeping Parameter Definition File for ASPOC on CLUSTER 1 */
HkextractAdidECLUP108 = 207,	 /* Housekeeping Parameter Definition File for SC on CLUSTER 1 */
HkextractAdidECLUP201 = 208,	 /* Housekeeping Parameter Definition File for EDI on CLUSTER 1 */
HkextractAdidECLUP202 = 209,	 /* Housekeeping Parameter Definition File for FGM on CLUSTER 1 */
HkextractAdidECLUP203 = 210,	 /* Housekeeping Parameter Definition File for CIS on CLUSTER 1 */
HkextractAdidECLUP204 = 211,	 /* Housekeeping Parameter Definition File for PEACE on CLUSTER 1 */
HkextractAdidECLUP205 = 212,	 /* Housekeeping Parameter Definition File for RAPID on CLUSTER 1 */
HkextractAdidECLUP206 = 213,	 /* Housekeeping Parameter Definition File for WEC on CLUSTER 1 */
HkextractAdidECLUP207 = 214,	 /* Housekeeping Parameter Definition File for ASPOC on CLUSTER 1 */
HkextractAdidECLUP208 = 215,	 /* Housekeeping Parameter Definition File for SC on CLUSTER 1 */
HkextractAdidECLUP301 = 216,	 /* Housekeeping Parameter Definition File for EDI on CLUSTER 1 */
HkextractAdidECLUP302 = 217,	 /* Housekeeping Parameter Definition File for FGM on CLUSTER 1 */
HkextractAdidECLUP303 = 218,	 /* Housekeeping Parameter Definition File for CIS on CLUSTER 1 */
HkextractAdidECLUP304 = 219,	 /* Housekeeping Parameter Definition File for PEACE on CLUSTER 1 */
HkextractAdidECLUP305 = 220,	 /* Housekeeping Parameter Definition File for RAPID on CLUSTER 1 */
HkextractAdidECLUP306 = 221,	 /* Housekeeping Parameter Definition File for WEC on CLUSTER 1 */
HkextractAdidECLUP307 = 222,	 /* Housekeeping Parameter Definition File for ASPOC on CLUSTER 1 */
HkextractAdidECLUP308 = 223,	 /* Housekeeping Parameter Definition File for SC on CLUSTER 1 */
HkextractAdidECLUP401 = 224,	 /* Housekeeping Parameter Definition File for EDI on CLUSTER 1 */
HkextractAdidECLUP402 = 225,	 /* Housekeeping Parameter Definition File for FGM on CLUSTER 1 */
HkextractAdidECLUP403 = 226,	 /* Housekeeping Parameter Definition File for CIS on CLUSTER 1 */
HkextractAdidECLUP404 = 227,	 /* Housekeeping Parameter Definition File for PEACE on CLUSTER 1 */
HkextractAdidECLUP405 = 228,	 /* Housekeeping Parameter Definition File for RAPID on CLUSTER 1 */
HkextractAdidECLUP406 = 229,	 /* Housekeeping Parameter Definition File for WEC on CLUSTER 1 */
HkextractAdidECLUP407 = 230,	 /* Housekeeping Parameter Definition File for ASPOC on CLUSTER 1 */
HkextractAdidECLUP408 = 231,	 /* Housekeeping Parameter Definition File for SC on CLUSTER 1 */
HkextractAdidECLUN101 = 30,	 /* Normal science data for EDI on Cluster 1 */
HkextractAdidECLUN102 = 31,	 /* Normal science data for FGM on Cluster 1 */
HkextractAdidECLUN103 = 32,	 /* Normal science data for CIS on Cluster 1 */
HkextractAdidECLUN104 = 33,	 /* Normal science data for PEACE on Cluster 1 */
HkextractAdidECLUN105 = 34,	 /* Normal science data for RAPID on Cluster 1 */
HkextractAdidECLUN106 = 35,	 /* Normal science data for WEC on Cluster 1 */
HkextractAdidECLUB101 = 37,	 /* Burst science data for EDI on Cluster 1 */
HkextractAdidECLUB102 = 38,	 /* Burst science data for FGM on Cluster 1 */
HkextractAdidECLUB103 = 39,	 /* Burst science data for CIS on Cluster 1 */
HkextractAdidECLUB104 = 40,	 /* Burst science data for PEACE on Cluster 1 */
HkextractAdidECLUB105 = 41,	 /* Burst science data for RAPID on Cluster 1 */
HkextractAdidECLUB106 = 42,	 /* Burst science data for WEC on Cluster 1 */
HkextractAdidECLUH101 = 44,	 /* Housekeeping data for EDI on Cluster 1 */
HkextractAdidECLUH102 = 45,	 /* Housekeeping data for FGM on Cluster 1 */
HkextractAdidECLUH103 = 46,	 /* Housekeeping data for CIS on Cluster 1 */
HkextractAdidECLUH104 = 47,	 /* Housekeeping data for PEACE on Cluster 1 */
HkextractAdidECLUH105 = 48,	 /* Housekeeping data for RAPID on Cluster 1 */
HkextractAdidECLUH106 = 49,	 /* Housekeeping data for WEC on Cluster 1 */
HkextractAdidECLUH107 = 50,	 /* Housekeeping data for ASPOC on Cluster 1 */
HkextractAdidECLUH108 = 51,	 /* Housekeeping data for Cluster 1 Platform */
HkextractAdidECLUN201 = 70,	 /* Normal science data for EDI on Cluster 2 */
HkextractAdidECLUN202 = 71,	 /* Normal science data for FGM on Cluster 2 */
HkextractAdidECLUN203 = 72,	 /* Normal science data for CIS on Cluster 2 */
HkextractAdidECLUN204 = 73,	 /* Normal science data for PEACE on Cluster 2 */
HkextractAdidECLUN205 = 74,	 /* Normal science data for RAPID on Cluster 2 */
HkextractAdidECLUN206 = 75,	 /* Normal science data for WEC on Cluster 2 */
HkextractAdidECLUB201 = 77,	 /* Burst science data for EDI on Cluster 2 */
HkextractAdidECLUB202 = 78,	 /* Burst science data for FGM on Cluster 2 */
HkextractAdidECLUB203 = 79,	 /* Burst science data for CIS on Cluster 2 */
HkextractAdidECLUB204 = 80,	 /* Burst science data for PEACE on Cluster 2 */
HkextractAdidECLUB205 = 81,	 /* Burst science data for RAPID on Cluster 2 */
HkextractAdidECLUB206 = 82,	 /* Burst science data for WEC on Cluster 2 */
HkextractAdidECLUH201 = 84,	 /* Housekeeping data for EDI on Cluster 2 */
HkextractAdidECLUH202 = 85,	 /* Housekeeping data for FGM on Cluster 2 */
HkextractAdidECLUH203 = 86,	 /* Housekeeping data for CIS on Cluster 2 */
HkextractAdidECLUH204 = 87,	 /* Housekeeping data for PEACE on Cluster 2 */
HkextractAdidECLUH205 = 88,	 /* Housekeeping data for RAPID on Cluster 2 */
HkextractAdidECLUH206 = 89,	 /* Housekeeping data for WEC on Cluster 2 */
HkextractAdidECLUH207 = 90,	 /* Housekeeping data for ASPOC on Cluster 2 */
HkextractAdidECLUH208 = 91,	 /* Housekeeping data for Cluster 2 Platform */
HkextractAdidECLUN301 = 110,	 /* Normal science data for EDI on Cluster 3 */
HkextractAdidECLUN302 = 111,	 /* Normal science data for FGM on Cluster 3 */
HkextractAdidECLUN303 = 112,	 /* Normal science data for CIS on Cluster 3 */
HkextractAdidECLUN304 = 113,	 /* Normal science data for PEACE on Cluster 3 */
HkextractAdidECLUN305 = 114,	 /* Normal science data for RAPID on Cluster 3 */
HkextractAdidECLUN306 = 115,	 /* Normal science data for WEC on Cluster 3 */
HkextractAdidECLUB301 = 117,	 /* Burst science data for EDI on Cluster 3 */
HkextractAdidECLUB302 = 118,	 /* Burst science data for FGM on Cluster 3 */
HkextractAdidECLUB303 = 119,	 /* Burst science data for CIS on Cluster 3 */
HkextractAdidECLUB304 = 120,	 /* Burst science data for PEACE on Cluster 3 */
HkextractAdidECLUB305 = 121,	 /* Burst science data for RAPID on Cluster 3 */
HkextractAdidECLUB306 = 122,	 /* Burst science data for WEC on Cluster 3 */
HkextractAdidECLUH301 = 124,	 /* Housekeeping data for EDI on Cluster 3 */
HkextractAdidECLUH302 = 125,	 /* Housekeeping data for FGM on Cluster 3 */
HkextractAdidECLUH303 = 126,	 /* Housekeeping data for CIS on Cluster 3 */
HkextractAdidECLUH304 = 127,	 /* Housekeeping data for PEACE on Cluster 3 */
HkextractAdidECLUH305 = 128,	 /* Housekeeping data for RAPID on Cluster 3 */
HkextractAdidECLUH306 = 129,	 /* Housekeeping data for WEC on Cluster 3 */
HkextractAdidECLUH307 = 130,	 /* Housekeeping data for ASPOC on Cluster 3 */
HkextractAdidECLUH308 = 131,	 /* Housekeeping data for Cluster 3 Platform */
HkextractAdidECLUN401 = 150,	 /* Normal science data for EDI on Cluster 4 */
HkextractAdidECLUN402 = 151,	 /* Normal science data for FGM on Cluster 4 */
HkextractAdidECLUN403 = 152,	 /* Normal science data for CIS on Cluster 4 */
HkextractAdidECLUN404 = 153,	 /* Normal science data for PEACE on Cluster 4 */
HkextractAdidECLUN405 = 154,	 /* Normal science data for RAPID on Cluster 4 */
HkextractAdidECLUN406 = 155,	 /* Normal science data for WEC on Cluster 4 */
HkextractAdidECLUB401 = 157,	 /* Burst science data for EDI on Cluster 4 */
HkextractAdidECLUB402 = 158,	 /* Burst science data for FGM on Cluster 4 */
HkextractAdidECLUB403 = 159,	 /* Burst science data for CIS on Cluster 4 */
HkextractAdidECLUB404 = 160,	 /* Burst science data for PEACE on Cluster 4 */
HkextractAdidECLUB405 = 161,	 /* Burst science data for RAPID on Cluster 4 */
HkextractAdidECLUB406 = 162,	 /* Burst science data for WEC on Cluster 4 */
HkextractAdidECLUH401 = 164,	 /* Housekeeping data for EDI on Cluster 4 */
HkextractAdidECLUH402 = 165,	 /* Housekeeping data for FGM on Cluster 4 */
HkextractAdidECLUH403 = 166,	 /* Housekeeping data for CIS on Cluster 4 */
HkextractAdidECLUH404 = 167,	 /* Housekeeping data for PEACE on Cluster 4 */
HkextractAdidECLUH405 = 168,	 /* Housekeeping data for RAPID on Cluster 4 */
HkextractAdidECLUH406 = 169,	 /* Housekeeping data for WEC on Cluster 4 */
HkextractAdidECLUH407 = 170,	 /* Housekeeping data for ASPOC on Cluster 4 */
HkextractAdidECLUH408 = 171	 /* Housekeeping data for Cluster 4 Platform */
} HkextractAdid;
#endif
