/* SDTInstanceXDR.h */
/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */
/* This file contains declarations for RPC-XDR for SDTInsance widgits: */

#ifndef SDTINSTANCEXDR_H
#define SDTINSTANCEXDR_H

/* SCCS ID string: */
#define SccsId_SDTInstanceXDR_h "@(#)SDTInstanceXDR.h	1.5, 02/24/04"

#ifndef SUNOS4
#ifdef __cplusplus
extern "C" {
#endif
#endif

#include <rpc/rpc.h>

#include <SDTInstance.h>
#include <SDTDescriptionXDR.h>

#ifndef _RPC_HNDL_FNC
#define _RPC_HNDL_FNC

/* Type declaration for SDT RPC Handler functions: */
typedef void (*SDTRPCHandlerFnc) (struct svc_req *rqstp, SVCXPRT *transp) ;
#endif /* ifndef _RPC_HNDL_FNC */

extern bool_t xdr_DataQuantityInstance_struct(XDR *, struct DataQuantityInstance_struct *);

extern bool_t xdr_DataQuantityInstance(XDR *, DataQuantityInstance *);

extern bool_t xdr_DataQuantityInstanceList_struct(XDR *, struct DataQuantityInstanceList_struct *);

extern bool_t xdr_DataQuantityInstanceList(XDR *, DataQuantityInstanceList *);

#ifndef SUNOS4
#ifdef __cplusplus
}
#endif
#endif

#endif /* SDTINSTANCEXDR_H */
