/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _UDPPORTINFO_H_RPCGEN
#define _UDPPORTINFO_H_RPCGEN

#include <rpc/rpc.h>

#include <pthread.h>

#ifdef __cplusplus
extern "C" {
#endif

#include "telemParams.h"
#include "relays.h"

struct udpPortInfo {
	int apIdTable[MAX_N_APP_IDS];
	int vcIdTable[N_VC_IDS];
	int nPorts;
};
typedef struct udpPortInfo udpPortInfo;

struct udpPortInfo_res {
	int error;
	union {
		udpPortInfo upi;
		char *errstring;
	} udpPortInfo_res_u;
};
typedef struct udpPortInfo_res udpPortInfo_res;
#include "multPort.h"

#define UDPPORTINFOPROG 600006000
#define UDPPORTINFOVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GETUDPPORTINFO 1
extern  enum clnt_stat getudpportinfo_1(void *, udpPortInfo_res *, CLIENT *);
extern  bool_t getudpportinfo_1_svc(void *, udpPortInfo_res *, struct svc_req *);
extern int udpportinfoprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GETUDPPORTINFO 1
extern  enum clnt_stat getudpportinfo_1();
extern  bool_t getudpportinfo_1_svc();
extern int udpportinfoprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_udpPortInfo (XDR *, udpPortInfo*);
extern  bool_t xdr_udpPortInfo_res (XDR *, udpPortInfo_res*);

#else /* K&R C */
extern bool_t xdr_udpPortInfo ();
extern bool_t xdr_udpPortInfo_res ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_UDPPORTINFO_H_RPCGEN */
